// Generated by Haxe 4.0.0-preview.4
(function ($hx_exports) { "use strict";
var $hxEnums = $hxEnums || {};
var HxOverrides = function() { };
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.has = function(it,elt) {
	var x = $getIterator(it);
	while(x.hasNext()) {
		var x1 = x.next();
		if(x1 == elt) {
			return true;
		}
	}
	return false;
};
var VideoPlayer = function(state) {
	this.shouldPlay = false;
	var _gthis = this;
	this.file = new atom_File(state.path);
	this.element = window.document.createElement("div");
	this.element.classList.add("videoplayer");
	this.element.setAttribute("tabindex","-1");
	if(!atom.config.get("videoplayer.background.transparent")) {
		this.element.style.background = atom.config.get("videoplayer.background.color").toHexString();
	}
	this.video = window.document.createElement("video");
	this.video.controls = true;
	this.video.src = this.file.getPath();
	this.element.appendChild(this.video);
	this.element.addEventListener("DOMNodeInserted",$bind(this,this.handleInsertDOM),false);
	this.video.addEventListener("canplaythrough",$bind(this,this.handleVideoCanPlay),false);
	this.video.addEventListener("playing",$bind(this,this.handleVideoPlay),false);
	this.video.addEventListener("ended",$bind(this,this.handleVideoEnd),false);
	this.video.addEventListener("error",$bind(this,this.handleVideoError),false);
	this.commands = new atom_CompositeDisposable();
	this.addCommand("play",function(e) {
		if(_gthis.video.paused) {
			_gthis.video.play();
		} else {
			_gthis.video.pause();
		}
		return;
	});
	this.addCommand("mute",function(e1) {
		_gthis.video.muted = !_gthis.video.muted;
		return;
	});
	this.addCommand("seek-forward",function(e2) {
		var ev = e2.originalEvent;
		var v;
		var _g = ev.keyCode;
		switch(_g) {
		case 33:
			v = 600;
			break;
		case 39:
			v = ev.shiftKey ? 60 : 10;
			break;
		default:
			v = 10;
		}
		return _gthis.seek(v);
	});
	this.addCommand("seek-backward",function(e3) {
		var ev1 = e3.originalEvent;
		var v1;
		var _g1 = ev1.keyCode;
		switch(_g1) {
		case 34:
			v1 = 600;
			break;
		case 37:
			v1 = ev1.shiftKey ? 60 : 10;
			break;
		default:
			v1 = 10;
		}
		return _gthis.seek(-v1);
	});
	this.addCommand("volume-increase",function(e4) {
		return _gthis.video.volume = Math.min(_gthis.video.volume + 0.1,1.0);
	});
	this.addCommand("volume-decrease",function(e5) {
		return _gthis.video.volume = Math.max(_gthis.video.volume - 0.1,0.0);
	});
	this.addCommand("toggle-fullscreen",function(e6) {
		_gthis.toggleFullscreen();
		return;
	});
	this.addCommand("goto-start",function(e7) {
		return _gthis.video.currentTime = 0;
	});
	this.addCommand("screenshot",function(e8) {
		var canvas = window.document.createElement("canvas");
		canvas.width = _gthis.video.videoWidth;
		canvas.height = _gthis.video.videoHeight;
		var ctx = canvas.getContext("2d");
		ctx.drawImage(_gthis.video,0,0,canvas.width,canvas.height);
		var dataURI = canvas.toDataURL("image/png");
		dataURI = HxOverrides.substr(dataURI,22,null);
		js_node_Fs.writeFile("screenshot_" + _gthis.video.currentTime + ".png",dataURI,{ encoding : "base64"},function(e9) {
			console.log("src/VideoPlayer.hx:165:",e9);
		});
		return;
	});
	if(state != null) {
		console.log("src/VideoPlayer.hx:188:",state);
		if(state.time != null) {
			this.video.currentTime = state.time;
		}
		if(state.volume != null) {
			this.video.volume = state.volume;
		}
		if(state.mute) {
			this.video.muted = true;
		}
		if(state.play) {
			this.shouldPlay = true;
		}
	}
};
VideoPlayer.activate = $hx_exports["activate"] = function(state) {
	VideoPlayer.disposables = new atom_CompositeDisposable();
	VideoPlayer.disposables.add(atom.workspace.addOpener(VideoPlayer.openURI));
	VideoPlayer.disposables.add(atom.workspace.onDidChangeActivePaneItem(function(item) {
		if((item instanceof VideoPlayer)) {
			var player = item;
			var video = player.video;
			VideoPlayer.statusbar.textContent = video.videoWidth + "x" + video.videoHeight;
		} else {
			VideoPlayer.statusbar.textContent = "";
		}
	}));
};
VideoPlayer.deactivate = $hx_exports["deactivate"] = function() {
	VideoPlayer.disposables.dispose();
	if(VideoPlayer.statusbar != null) {
		VideoPlayer.statusbar.remove();
	}
};
VideoPlayer.deserialize = $hx_exports["deserialize"] = function(state) {
	return new VideoPlayer(state);
};
VideoPlayer.openURI = function(uri) {
	var ext = haxe_io_Path.extension(uri).toLowerCase();
	if(Lambda.has(VideoPlayer.allowedFileTypes,ext)) {
		var player = new VideoPlayer({ path : uri, time : null, volume : atom.config.get("videoplayer.playback.volume"), play : atom.config.get("videoplayer.playback.autoplay"), mute : false});
		VideoPlayer.disposables.add(player);
		return player;
	}
	return null;
};
VideoPlayer.consumeStatusBar = $hx_exports["consumeStatusBar"] = function(pane) {
	if(VideoPlayer.statusbar == null) {
		VideoPlayer.statusbar = window.document.createElement("div");
		VideoPlayer.statusbar.classList.add("status-bar-videoplayer","inline-block");
		pane.addLeftTile({ item : VideoPlayer.statusbar});
	}
};
VideoPlayer.prototype = {
	serialize: function() {
		return { deserializer : "VideoPlayer", path : this.file.getPath(), time : this.video.currentTime, play : !this.video.paused, mute : this.video.muted, volume : this.video.volume};
	}
	,dispose: function() {
		this.commands.dispose();
		this.element.removeEventListener("DOMNodeInserted",$bind(this,this.handleInsertDOM));
		this.video.removeEventListener("canplaythrough",$bind(this,this.handleVideoCanPlay));
		this.video.removeEventListener("playing",$bind(this,this.handleVideoPlay));
		this.video.removeEventListener("ended",$bind(this,this.handleVideoEnd));
		this.video.removeEventListener("error",$bind(this,this.handleVideoError));
		this.video.removeEventListener("click",$bind(this,this.handleVideoClick));
		this.video.removeEventListener("mousewheel",$bind(this,this.handleMouseWheel));
		this.video.remove();
		this.video = null;
	}
	,getPath: function() {
		return this.file.getPath();
	}
	,getTitle: function() {
		return this.file.getBaseName();
	}
	,getIconName: function() {
		return "file-media";
	}
	,getURI: function() {
		return this.getPath();
	}
	,getEncodedURI: function() {
		var s = this.getPath();
		return "file://" + encodeURIComponent(s);
	}
	,isEqual: function(other) {
		return (other instanceof VideoPlayer);
	}
	,addCommand: function(name,fn) {
		this.commands.add(atom.commands.add(this.element,"videoplayer:" + name,fn));
	}
	,seek: function(secs) {
		this.video.currentTime += secs;
		return this.video.currentTime;
	}
	,togglePlayback: function() {
		if(this.video.paused) {
			this.video.play();
		} else {
			this.video.pause();
		}
	}
	,toggleMute: function() {
		this.video.muted = !this.video.muted;
	}
	,toggleFullscreen: function() {
		if(atom.isFullScreen()) {
			window.document.webkitExitFullscreen();
		} else {
			this.video.webkitRequestFullscreen();
		}
	}
	,handleInsertDOM: function(e) {
	}
	,handleVideoCanPlay: function(e) {
		this.video.removeEventListener("canplaythrough",$bind(this,this.handleVideoCanPlay));
		this.video.addEventListener("click",$bind(this,this.handleVideoClick),false);
		this.video.addEventListener("mousewheel",$bind(this,this.handleMouseWheel),false);
		if(this.shouldPlay) {
			this.shouldPlay = false;
			this.video.play();
		}
	}
	,handleVideoPlay: function(e) {
		VideoPlayer.statusbar.textContent = this.video.videoWidth + "x" + this.video.videoHeight;
	}
	,handleVideoEnd: function(e) {
		if(atom.config.get("videoplayer.playback.loop")) {
			this.video.play();
		}
	}
	,handleVideoError: function(e) {
		atom.notifications.addError("Cannot play video: " + this.getPath());
		console.error(e);
	}
	,handleVideoClick: function(e) {
		if(this.video.paused) {
			this.video.play();
		} else {
			this.video.pause();
		}
	}
	,handleMouseWheel: function(e) {
		var v = e.wheelDelta < 0 ? -1 : 1;
		if(e.shiftKey) {
			v *= 10;
		}
		this.seek(v);
	}
};
var atom_CompositeDisposable = require("atom").CompositeDisposable;
var atom_File = require("atom").File;
var haxe_io_Bytes = function(data) {
	this.length = data.byteLength;
	this.b = new Uint8Array(data);
	this.b.bufferValue = data;
	data.hxBytes = this;
	data.bytes = this.b;
};
haxe_io_Bytes.alloc = function(length) {
	return new haxe_io_Bytes(new ArrayBuffer(length));
};
haxe_io_Bytes.ofString = function(s) {
	var a = [];
	var i = 0;
	while(i < s.length) {
		var c = s.charCodeAt(i++);
		if(55296 <= c && c <= 56319) {
			c = c - 55232 << 10 | s.charCodeAt(i++) & 1023;
		}
		if(c <= 127) {
			a.push(c);
		} else if(c <= 2047) {
			a.push(192 | c >> 6);
			a.push(128 | c & 63);
		} else if(c <= 65535) {
			a.push(224 | c >> 12);
			a.push(128 | c >> 6 & 63);
			a.push(128 | c & 63);
		} else {
			a.push(240 | c >> 18);
			a.push(128 | c >> 12 & 63);
			a.push(128 | c >> 6 & 63);
			a.push(128 | c & 63);
		}
	}
	return new haxe_io_Bytes(new Uint8Array(a).buffer);
};
haxe_io_Bytes.ofData = function(b) {
	var hb = b.hxBytes;
	if(hb != null) {
		return hb;
	}
	return new haxe_io_Bytes(b);
};
haxe_io_Bytes.fastGet = function(b,pos) {
	return b.bytes[pos];
};
var haxe_io_Path = function(path) {
	switch(path) {
	case ".":case "..":
		this.dir = path;
		this.file = "";
		return;
	}
	var c1 = path.lastIndexOf("/");
	var c2 = path.lastIndexOf("\\");
	if(c1 < c2) {
		this.dir = HxOverrides.substr(path,0,c2);
		path = HxOverrides.substr(path,c2 + 1,null);
		this.backslash = true;
	} else if(c2 < c1) {
		this.dir = HxOverrides.substr(path,0,c1);
		path = HxOverrides.substr(path,c1 + 1,null);
	} else {
		this.dir = null;
	}
	var cp = path.lastIndexOf(".");
	if(cp != -1) {
		this.ext = HxOverrides.substr(path,cp + 1,null);
		this.file = HxOverrides.substr(path,0,cp);
	} else {
		this.ext = null;
		this.file = path;
	}
};
haxe_io_Path.extension = function(path) {
	var s = new haxe_io_Path(path);
	if(s.ext == null) {
		return "";
	}
	return s.ext;
};
var js_node_Fs = require("fs");
function $getIterator(o) { if( o instanceof Array ) return HxOverrides.iter(o); else return o.iterator(); }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
VideoPlayer.allowedFileTypes = ["3gp","avi","mov","mp4","m4v","mkv","ogv","ogm","webm"];
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this);
