"undefined"!==typeof process&&"v4.0.0">process.version&&console.warn("Module "+("undefined"==typeof module?"":module.filename)+" requires node.js version 4.0.0 or higher");
(function(r,t){function u(a){return a instanceof Array?function(){return f.iter(a)}:"function"==typeof a.iterator?l(a,a.iterator):a.iterator}function l(a,b){if(null==b)return null;null==b.__id__&&(b.__id__=v++);var c;null==a.hx__closures__?a.hx__closures__={}:c=a.hx__closures__[b.__id__];null==c&&(c=function(){return c.method.apply(c.scope,arguments)},c.scope=a,c.method=b,a.hx__closures__[b.__id__]=c);return c}var f=function(){};f.__name__=!0;f.substr=function(a,b,c){if(null==c)c=a.length;else if(0>
c)if(0==b)c=a.length+c;else return"";return a.substr(b,c)};f.iter=function(a){return{cur:0,arr:a,hasNext:function(){return this.cur<this.arr.length},next:function(){return this.arr[this.cur++]}}};var n=function(){};n.__name__=!0;n.has=function(a,b){for(var c=u(a)();c.hasNext();)if(c.next()==b)return!0;return!1};Math.__name__=!0;var m=function(){};m.__name__=!0;m.string=function(a){return e.__string_rec(a,"")};var d=r.VideoPlayer=function(a){var b=this;this.file=new w(a.path);this.wheelSpeed=1;window.getComputedStyle(atom.views.getView(atom.workspace));
this.element=window.document.createElement("div");this.element.classList.add("videoplayer");this.element.setAttribute("tabindex","-1");this.video=window.document.createElement("video");this.video.controls=!0;this.video.src=this.file.getPath();null!=a.play&&(this.video.autoplay=a.play);null!=a.time&&(this.video.currentTime=a.time);this.element.appendChild(this.video);this.element.addEventListener("DOMNodeInserted",function(){b.video.addEventListener("canplaythrough",function(a){b.element.addEventListener("mousewheel",
l(b,b.handleMouseWheel),!1)});window.addEventListener("resize",l(b,b.handleResize),!1)},!1)};d.__name__=!0;d.activate=function(a){d.disposables=new x;d.disposables.add(atom.workspace.addOpener(d.openURI))};d.deactivate=function(){d.disposables.dispose()};d.openURI=function(a){var b=h.extension(a).toLowerCase();return n.has(d.allowedFileTypes,b)?new d({path:a,play:atom.config.get("video.autoplay"),time:null}):null};d.consumeStatusBar=function(a){};d.deserialize=function(a){return new d(a)};d.prototype=
{serialize:function(){return{deserializer:"VideoPlayer",path:this.file.getPath(),play:!this.video.paused,time:this.video.currentTime}},dispose:function(){this.video.pause();this.video.remove();this.video=null},getPath:function(){return this.file.getPath()},getTitle:function(){return this.file.getBaseName()},getURI:function(){var a=this.file.getPath();return"file://"+encodeURIComponent(a)},isEqual:function(a){return e.__instanceof(a,d)?this.getURI()==e.__cast(a,d).getURI():!1},update:function(a){this.animationFrameId=
window.requestAnimationFrame(l(this,this.update))},seek:function(a){null!=this.video.currentTime&&(this.video.currentTime+=a);return this.video.currentTime},updateMarker:function(){},handleAudioPlaying:function(a){this.animationFrameId=window.requestAnimationFrame(l(this,this.update))},handleAudioEnded:function(a){},handleAudioError:function(a){},handleMouseDown:function(a){},handleMouseUp:function(a){},handleMouseOut:function(a){},handleMouseWheel:function(a){var b=a.wheelDelta/100*this.wheelSpeed;
a.ctrlKey&&(b*=10,a.shiftKey&&(b*=10));this.seek(b)},handleResize:function(a){},__class__:d};var x=require("atom").CompositeDisposable,w=require("atom").File,h=function(a){switch(a){case ".":case "..":this.dir=a;this.file="";return}var b=a.lastIndexOf("/"),c=a.lastIndexOf("\\");b<c?(this.dir=f.substr(a,0,c),a=f.substr(a,c+1,null),this.backslash=!0):c<b?(this.dir=f.substr(a,0,b),a=f.substr(a,b+1,null)):this.dir=null;b=a.lastIndexOf(".");-1!=b?(this.ext=f.substr(a,b+1,null),this.file=f.substr(a,0,b)):
(this.ext=null,this.file=a)};h.__name__=!0;h.extension=function(a){a=new h(a);return null==a.ext?"":a.ext};h.prototype={__class__:h};var g=function(a){Error.call(this);this.val=a;this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,g)};g.__name__=!0;g.wrap=function(a){return a instanceof Error?a:new g(a)};g.__super__=Error;g.prototype=function(a,b){function c(){}c.prototype=a;var e=new c,d;for(d in b)e[d]=b[d];b.toString!==Object.prototype.toString&&(e.toString=b.toString);
return e}(Error.prototype,{__class__:g});var e=function(){};e.__name__=!0;e.getClass=function(a){if(a instanceof Array&&null==a.__enum__)return Array;var b=a.__class__;if(null!=b)return b;a=e.__nativeClassName(a);return null!=a?e.__resolveNativeClass(a):null};e.__string_rec=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.__name__||a.__ename__)&&(c="object");switch(c){case "function":return"<function>";case "object":if(a instanceof Array){if(a.__enum__){if(2==
a.length)return a[0];c=a[0]+"(";b+="\t";for(var d=2,f=a.length;d<f;)var k=d++,c=2!=k?c+(","+e.__string_rec(a[k],b)):c+e.__string_rec(a[k],b);return c+")"}c=a.length;d="[";b+="\t";for(f=0;f<c;)k=f++,d+=(0<k?",":"")+e.__string_rec(a[k],b);return d+"]"}try{d=a.toString}catch(g){return"???"}if(null!=d&&d!=Object.toString&&"function"==typeof d&&(c=a.toString(),"[object Object]"!=c))return c;c=null;d="{\n";b+="\t";f=null!=a.hasOwnProperty;for(c in a)f&&!a.hasOwnProperty(c)||"prototype"==c||"__class__"==
c||"__super__"==c||"__interfaces__"==c||"__properties__"==c||(2!=d.length&&(d+=", \n"),d+=b+c+" : "+e.__string_rec(a[c],b));b=b.substring(1);return d+("\n"+b+"}");case "string":return a;default:return String(a)}};e.__interfLoop=function(a,b){if(null==a)return!1;if(a==b)return!0;var c=a.__interfaces__;if(null!=c)for(var d=0,f=c.length;d<f;){var g=c[d++];if(g==b||e.__interfLoop(g,b))return!0}return e.__interfLoop(a.__super__,b)};e.__instanceof=function(a,b){if(null==b)return!1;switch(b){case Array:return a instanceof
Array?null==a.__enum__:!1;case p:return"boolean"==typeof a;case y:return!0;case q:return"number"==typeof a;case z:return"number"==typeof a?(a|0)===a:!1;case String:return"string"==typeof a;default:if(null!=a)if("function"==typeof b){if(a instanceof b||e.__interfLoop(e.getClass(a),b))return!0}else{if("object"==typeof b&&e.__isNativeObj(b)&&a instanceof b)return!0}else return!1;return b==A&&null!=a.__name__||b==B&&null!=a.__ename__?!0:a.__enum__==b}};e.__cast=function(a,b){if(e.__instanceof(a,b))return a;
throw new g("Cannot cast "+m.string(a)+" to "+m.string(b));};e.__nativeClassName=function(a){a=e.__toStr.call(a).slice(8,-1);return"Object"==a||"Function"==a||"Math"==a||"JSON"==a?null:a};e.__isNativeObj=function(a){return null!=e.__nativeClassName(a)};e.__resolveNativeClass=function(a){return t[a]};require("buffer");var v=0;String.prototype.__class__=String;String.__name__=!0;Array.__name__=!0;var z={__name__:["Int"]},y={__name__:["Dynamic"]},q=Number;q.__name__=["Float"];var p=Boolean;p.__ename__=
["Bool"];var A={__name__:["Class"]},B={};module.exports=d;d.allowedFileTypes="3gp avi mov mp4 m4v mkv ogv ogm webm".split(" ");e.__toStr={}.toString})("undefined"!=typeof exports?exports:"undefined"!=typeof window?window:"undefined"!=typeof self?self:this,"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this);
