// Generated by Haxe 3.3.0
if (typeof process !== "undefined") if (process.version < "v4.0.0") console.warn("Module " + (typeof(module) == "undefined" ? "" : module.filename) + " requires node.js version 4.0.0 or higher");

(function ($hx_exports, $global) { "use strict";
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Lambda = function() { };
Lambda.__name__ = true;
Lambda.has = function(it,elt) {
	var tmp = $iterator(it)();
	while(tmp.hasNext()) if(tmp.next() == elt) {
		return true;
	}
	return false;
};
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
var atom_CompositeDisposable = require("atom").CompositeDisposable;
var VideoPlayerView = $hx_exports["VideoPlayerView"] = function(player) {
	var _gthis = this;
	this.player = player;
	this.wheelSpeed = 1;
	var workspaceStyle = window.getComputedStyle(atom.views.getView(atom.workspace));
	this.element = window.document.createElement("div");
	this.element.classList.add("videoplayer");
	this.element.setAttribute("tabindex","-1");
	this.element.appendChild(player.video);
	this.element.addEventListener("DOMNodeInserted",function() {
		player.video.addEventListener("canplaythrough",function(e) {
			_gthis.element.addEventListener("mousewheel",$bind(_gthis,_gthis.handleMouseWheel),false);
		});
	},false);
	window.addEventListener("resize",$bind(this,this.handleResize),false);
};
VideoPlayerView.__name__ = true;
VideoPlayerView.prototype = {
	update: function(time) {
		this.animationFrameId = window.requestAnimationFrame($bind(this,this.update));
		this.updateMarker();
	}
	,seek: function(time) {
		if(this.player.video.currentTime != null) {
			this.player.video.currentTime += time;
		}
		return this.player.video.currentTime;
	}
	,updateMarker: function() {
	}
	,handleAudioPlaying: function(e) {
		this.animationFrameId = window.requestAnimationFrame($bind(this,this.update));
	}
	,handleAudioEnded: function(e) {
	}
	,handleAudioError: function(e) {
	}
	,handleMouseDown: function(e) {
	}
	,handleMouseUp: function(e) {
	}
	,handleMouseOut: function(e) {
	}
	,handleMouseWheel: function(e) {
		var v = e.wheelDelta / 100 * this.wheelSpeed;
		if(e.ctrlKey) {
			v *= 10;
			if(e.shiftKey) {
				v *= 10;
			}
		}
		this.seek(v);
	}
	,handleResize: function(e) {
	}
	,__class__: VideoPlayerView
};
var VideoPlayer = $hx_exports["VideoPlayer"] = function(path,play,time) {
	if(time == null) {
		time = 0.0;
	}
	this.file = new atom_File(path);
	this.video = window.document.createElement("video");
	this.video.autoplay = play;
	this.video.controls = true;
	this.video.src = this.file.getPath();
	this.video.currentTime = time;
};
VideoPlayer.__name__ = true;
VideoPlayer.activate = function(state) {
	console.log("Atom-videoplayer ");
	VideoPlayer.disposables.add(atom.workspace.addOpener(VideoPlayer.openURI));
};
VideoPlayer.deactivate = function() {
	VideoPlayer.disposables.dispose();
};
VideoPlayer.openURI = function(uri) {
	if(Lambda.has(VideoPlayer.allowedFileTypes,haxe_io_Path.extension(uri).toLowerCase())) {
		return new VideoPlayer(uri,atom.config.get("videoplayer.autoplay"));
	}
	return null;
};
VideoPlayer.consumeStatusBar = function(pane) {
};
VideoPlayer.deserialize = function(state) {
	return new VideoPlayer(state.path,state.play,state.time);
};
VideoPlayer.prototype = {
	serialize: function() {
		return { deserializer : "VideoPlayer", path : this.file.getPath(), play : !this.video.paused, time : this.video.currentTime};
	}
	,dispose: function() {
		this.video.pause();
		this.video.remove();
		this.video = null;
	}
	,getPath: function() {
		return this.file.getPath();
	}
	,getTitle: function() {
		return this.file.getBaseName();
	}
	,getURI: function() {
		var s = this.file.getPath();
		return "file://" + encodeURIComponent(s);
	}
	,isEqual: function(other) {
		if(!js_Boot.__instanceof(other,VideoPlayer)) {
			return false;
		}
		return this.getURI() == (js_Boot.__cast(other , VideoPlayer)).getURI();
	}
	,__class__: VideoPlayer
};
var atom_Disposable = function() { };
atom_Disposable.__name__ = true;
var atom_File = require("atom").File;
var haxe_io_Bytes = function() { };
haxe_io_Bytes.__name__ = true;
haxe_io_Bytes.prototype = {
	__class__: haxe_io_Bytes
};
var haxe_io_Path = function(path) {
	switch(path) {
	case ".":case "..":
		this.dir = path;
		this.file = "";
		return;
	}
	var c1 = path.lastIndexOf("/");
	var c2 = path.lastIndexOf("\\");
	if(c1 < c2) {
		this.dir = HxOverrides.substr(path,0,c2);
		path = HxOverrides.substr(path,c2 + 1,null);
		this.backslash = true;
	} else if(c2 < c1) {
		this.dir = HxOverrides.substr(path,0,c1);
		path = HxOverrides.substr(path,c1 + 1,null);
	} else {
		this.dir = null;
	}
	var cp = path.lastIndexOf(".");
	if(cp != -1) {
		this.ext = HxOverrides.substr(path,cp + 1,null);
		this.file = HxOverrides.substr(path,0,cp);
	} else {
		this.ext = null;
		this.file = path;
	}
};
haxe_io_Path.__name__ = true;
haxe_io_Path.extension = function(path) {
	var s = new haxe_io_Path(path);
	if(s.ext == null) {
		return "";
	}
	return s.ext;
};
haxe_io_Path.prototype = {
	__class__: haxe_io_Path
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.wrap = function(val) {
	if((val instanceof Error)) {
		return val;
	} else {
		return new js__$Boot_HaxeError(val);
	}
};
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) {
		return Array;
	} else {
		var cl = o.__class__;
		if(cl != null) {
			return cl;
		}
		var name = js_Boot.__nativeClassName(o);
		if(name != null) {
			return js_Boot.__resolveNativeClass(name);
		}
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) {
					return o[0];
				}
				var str = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i = _g1++;
					if(i != 2) {
						str += "," + js_Boot.__string_rec(o[i],s);
					} else {
						str += js_Boot.__string_rec(o[i],s);
					}
				}
				return str + ")";
			}
			var l = o.length;
			var i1;
			var str1 = "[";
			s += "\t";
			var _g11 = 0;
			var _g2 = l;
			while(_g11 < _g2) {
				var i2 = _g11++;
				str1 += (i2 > 0?",":"") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var k = null;
		var str2 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str2.length != 2) {
			str2 += ", \n";
		}
		str2 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str2 += "\n" + s + "}";
		return str2;
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) {
		return false;
	}
	if(cc == cl) {
		return true;
	}
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g1 = 0;
		var _g = intf.length;
		while(_g1 < _g) {
			var i = intf[_g1++];
			if(i == cl || js_Boot.__interfLoop(i,cl)) {
				return true;
			}
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) {
		return false;
	}
	switch(cl) {
	case Array:
		if((o instanceof Array)) {
			return o.__enum__ == null;
		} else {
			return false;
		}
		break;
	case Bool:
		return typeof(o) == "boolean";
	case Dynamic:
		return true;
	case Float:
		return typeof(o) == "number";
	case Int:
		if(typeof(o) == "number") {
			return (o|0) === o;
		} else {
			return false;
		}
		break;
	case String:
		return typeof(o) == "string";
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(o instanceof cl) {
					return true;
				}
				if(js_Boot.__interfLoop(js_Boot.getClass(o),cl)) {
					return true;
				}
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(o instanceof cl) {
					return true;
				}
			}
		} else {
			return false;
		}
		if(cl == Class && o.__name__ != null) {
			return true;
		}
		if(cl == Enum && o.__ename__ != null) {
			return true;
		}
		return o.__enum__ == cl;
	}
};
js_Boot.__cast = function(o,t) {
	if(js_Boot.__instanceof(o,t)) {
		return o;
	} else {
		throw new js__$Boot_HaxeError("Cannot cast " + Std.string(o) + " to " + Std.string(t));
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") {
		return null;
	}
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var js_node_buffer_Buffer = require("buffer").Buffer;
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
String.prototype.__class__ = String;
String.__name__ = true;
Array.__name__ = true;
var Int = { __name__ : ["Int"]};
var Dynamic = { __name__ : ["Dynamic"]};
var Float = Number;
Float.__name__ = ["Float"];
var Bool = Boolean;
Bool.__ename__ = ["Bool"];
var Class = { __name__ : ["Class"]};
var Enum = { };
module.exports = VideoPlayer;
VideoPlayer.disposables = new atom_CompositeDisposable();
VideoPlayer.disposables.add(atom.views.addViewProvider(VideoPlayer,function(player) {
	return new VideoPlayerView(player).element;
}));
VideoPlayer.allowedFileTypes = ["3gp","avi","mov","mp4","m4v","mkv","ogv","ogm","webm"];
js_Boot.__toStr = { }.toString;
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=videoplayer.js.map